Name:           ros-indigo-rocon-gateway-tests
Version:        0.7.5
Release:        0%{?dist}
Summary:        ROS rocon_gateway_tests package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/rocon_gateway_tests
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  ros-indigo-actionlib-tutorials
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-gateway-msgs
BuildRequires:  ros-indigo-rocon-console
BuildRequires:  ros-indigo-rocon-gateway
BuildRequires:  ros-indigo-rocon-gateway-utils
BuildRequires:  ros-indigo-rocon-hub
BuildRequires:  ros-indigo-rocon-test
BuildRequires:  ros-indigo-roscpp-tutorials
BuildRequires:  ros-indigo-rospy
BuildRequires:  ros-indigo-rospy-tutorials
BuildRequires:  ros-indigo-rosunit
BuildRequires:  ros-indigo-zeroconf-avahi

%description
Testing programs for gateways.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Tue Sep 23 2014 Daniel Stonier <d.stonier@gmail.com> - 0.7.5-0
- Autogenerated by Bloom

* Mon Aug 25 2014 Daniel Stonier <d.stonier@gmail.com> - 0.7.4-0
- Autogenerated by Bloom

